# Generated by Django 5.2 on 2025-04-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRIScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1ce', models.FileField(upload_to='mri_scans/t1ce/')),
                ('flair', models.FileField(upload_to='mri_scans/flair/')),
                ('slice_number', models.IntegerField(default=70)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
