# Generated by Django 5.2 on 2025-04-19 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuro_insight_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('pdf_report', models.FileField(upload_to='patient_reports/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='report_thumbnails/')),
                ('tumor_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
